scripts/start.sh

@akshayrai 
this log is super useful for debugging failures. any reason we should not merge this change?

fix start script to redirect output to a file instead of /dev/null

---

app/com/linkedin/drelephant/analysis/AnalyticJobGeneratorHadoop2.java

@akshayrai 
This patch gets the active resource manager by fetching the list of resource managers, and checking which one of them is active.
Tested on CDH 5.3 with HA enabled. 
Please tag whoever else need to review this.

Get the active resource manager URL when HA is enabled

---

project/Dependencies.scala

#14 introduced a new approach to reaching the resource manager. However, without this codec, you will run into `java.lang.NoSuchMethodError: org.apache.commons.codec.binary.Base64.<init>(I)V`.

Adding commons codec to the dependency

---

project/Dependencies.scala

This commit fixes #22 .
Spark 1.5.0 > has version `2.3.4-spark` for com.typesafe.akka packages (http://mvnrepository.com/artifact/org.apache.spark/spark-core_2.10/1.4.0). This is what the default config is.
If you have 1.5.0 < , version `2.3.11` (http://mvnrepository.com/artifact/org.apache.spark/spark-core_2.10/1.5.0) has a conflict with other akka dependencies required for dr. elephant. You need to exclude those packages.

Spark dependency resolution based on version

---

app/com/linkedin/drelephant/util/Utils.java
jacoco.sbt
project/plugins.sbt

…il.UtilsTest.testGetParam() is run
with code coverage. Turns out to be an sbt issue as noted here.
http://stackoverflow.com/questions/20168226/sbt-0-13-scriptengine-is-null-for-getenginebyname-javascript
Note:
1. All tests passed post this fix with and without code coverage
2. Application started without any issues

Adding code coverage to Dr. Elephant

---

app/com/linkedin/drelephant/analysis/AnalyticJobGeneratorHadoop2.java

Currently if there are multiple resource managers (i.e. HA mode) Dr. Elephant goes through each one and makes a request which it uses to determine which is currently active. The problem is, if any of these requests fail (which will happen if any node which is down is queried), the exception handling logic will cause the loop to break and stop the remaining nodes from having their status checked. This PR fixes that.
I'm from Airbnb. I tested this on CDH 5.3 with MapReduce 2.5.0 and Spark 1.5.2.
@krishnap @plypaul @hongbozeng @liyintang @brandtg

Try alternate resource manager if one is down

---

app-conf/FetcherConf.xml
app/org/apache/spark/deploy/history/SparkFSFetcher.scala

Since not everyone's Spark logs end in _1.snappy, I think it makes sense to add the Spark log extension as a conf param.
@krishnap @plypaul @hongbozeng @liyintang @brandtg @timyitong

Add spark log ext conf param

---

app/org/apache/spark/deploy/history/SparkFSFetcher.scala

Recent change (https://github.com/linkedin/dr-elephant/pull/79) broke the build:
```
[error] /tmp/dr-elephant/app/org/apache/spark/deploy/history/SparkFSFetcher.scala:240: value getOrDefault is not a member of java.util.Map[String,String]
[error]             val sparkLogExt = fetcherConfData.getParamMap.getOrDefault(SPARK_LOG_EXT, defSparkLogExt)
[error]                                                           ^
```
@paulbramsen have you tried compiling it after this minor change (https://github.com/linkedin/dr-elephant/pull/79#discussion_r67580363)?
@akshayrai @plypaul @krishnap

Fix fallback to default `SPARK_LOG_EXT` value

---

app-conf/SchedulerConf.xml
app/com/linkedin/drelephant/configurations/fetcher/FetcherConfiguration.java
app/com/linkedin/drelephant/configurations/heuristic/HeuristicConfiguration.java
app/com/linkedin/drelephant/configurations/scheduler/SchedulerConfiguration.java
app/com/linkedin/drelephant/configurations/scheduler/SchedulerConfigurationData.java
app/com/linkedin/drelephant/schedulers/AirflowScheduler.java
app/com/linkedin/drelephant/schedulers/AzkabanScheduler.java
app/com/linkedin/drelephant/schedulers/Scheduler.java
app/com/linkedin/drelephant/util/InfoExtractor.java
app/com/linkedin/drelephant/util/Utils.java
test/com/linkedin/drelephant/configurations/scheduler/SchedulerConfigurationTest.java
test/com/linkedin/drelephant/schedulers/AirflowSchedulerTest.java
test/com/linkedin/drelephant/schedulers/AzkabanSchedulerTest.java
test/com/linkedin/drelephant/util/InfoExtractorTest.java
test/com/linkedin/drelephant/util/UtilsTest.java
test/resources/SchedulerConf.xml
test/resources/configurations/scheduler/SchedulerConfTest1.xml
test/resources/configurations/scheduler/SchedulerConfTest2.xml
test/resources/configurations/scheduler/SchedulerConfTest3.xml

This commit gives Dr. Elephant the ability to ingest Airflow data in the same way it reads Azkaban data! It also makes adding additional schedulers in the future more inline with other stuff that is configurable in Dr. Elephant (i.e. there is a conf file). This PR also includes tests for the new Airflow capabilities.
@krishnap @plypaul @hongbozeng @liyintang @brandtg @timyitong
Note: This requires that your version of Airflow include the patch in this PR: https://github.com/apache/incubator-airflow/pull/1607. Currently only the Hive operator is supported but there is planned support for additional operators in the near future.

Add Airflow scheduler support to Dr. Elephant. Includes Tests.

---

app-conf/HeuristicConf.xml
app/com/linkedin/drelephant/mapreduce/heuristics/GenericMemoryHeuristic.java

Not everyone uses a 2GB default container size. This makes that property easily configurable in `HeuristicConf.xml`.
@krishnap

Make default container mem configurable

---

app/views/page/jobHistoryPage.scala.html

The job history page tab doesn't highlight when you are on that page. This PR fixes the problem.
@krishnap

Fix job history page tab highlighting

---

NOTICE
app-conf/elephant.conf
app/com/linkedin/drelephant/ElephantRunner.java
app/com/linkedin/drelephant/analysis/AnalyticJobGeneratorHadoop2.java
app/com/linkedin/drelephant/metrics/CustomGarbageCollectorMetricSet.java
app/controllers/MetricsController.java
conf/routes
project/Dependencies.scala
scripts/start.sh

Added Dropwizard metrics to Dr. Elephant. This change enables metrics by default.
Following endpoints are exposed
1) /ping
2) /healthcheck
3) /metrics
Following stats are available at present
1. Application status - /ping
2. Queue Size
3. Skipped Jobs Count
4. Retry Queue Size
5. Thread Deadlocks - /healthcheck
6. GC Count
7. GC Time
8. GC Count to JVM Uptime ratio
9. Heap Memory Usage stats

LIHADOOP-21568: Add Dropwizard metrics to Dr. Elephant

---

app/controllers/MetricsController.java

Without a default value, if the Boolean object couldn't find a metrics setting (i.e. it's not defined in someone's `elephant.conf`) `null` is returned. Then, the jvm attemtpts to autounbox `null` in order to evaluate the boolean expression. Instead of causing the expression to evaluate to false as one would expect, this results in a `NullPointerException` being thrown which crashes the main processing thread (i.e. the web ui will continue to run but no new data will be ingested).
@krishnap

Add default for boolean unboxing

---

app/com/linkedin/drelephant/util/InfoExtractor.java

I noticed some weird log output and realized that `InfoExtractor` was duplicating some of its loading work because of not being properly synchronized. This fixes that issue.
@krishnap

Fix sync issue in info extractor

---

app/com/linkedin/drelephant/ElephantRunner.java

This commit brings Dr. Elephant's main producer/consumer run loop in line with standard Java best practices by submitting tasks to a work queue as `Runnable`s making things much more robust.
Previously, if a worker thread's main while loop exited for any reason that thread would live on but would stop processing data forever since the Executor would sit waiting for additional work to be submitted. Essentially, the problem was that things were being done in a standard way and there were 2 queues. We noticed that every once in a while a worker thread's while loop would exit leading to stalled progress over time after they had all done this.
@krishnap

Modify main run loop to be inline with thread pool executor paradigms

---

app/controllers/Application.java

We've found having search result counts on the search page to be quite useful.
@krishnap

Show result count in search

---

app-conf/elephant.conf
scripts/start.sh

Changes to load an agent jar along with Dr. Elephant. Current use-case is to publish the metrics
to other applications. The property is disabled by default and users who wish to make use of this
specify their own agent jar.

Changes to load an agent jar along with Dr. Elephant.

---

app/com/linkedin/drelephant/schedulers/OozieScheduler.java
test/com/linkedin/drelephant/schedulers/OozieSchedulerTest.java

in superParentId, while( ... !isCoordinatorJob(extractId(parentId))) actually stopped our loop before finding the Coordinator parent. So subworkflows only returned their superparentworkflow, but not the coordinator launching that one.
also fixed testDepthCalculation - our test workflow only has one parent so Depth should be 1.

OozieScheduler: fix superParentId - now also returns the Coordinator id for subworkflows

---

app/com/linkedin/drelephant/ElephantContext.java
app/com/linkedin/drelephant/util/InfoExtractor.java

Classes can be easily loaded using the native Java libraries. Therefore, there is no need to use an external framework, Play, to load classes.

Removes dependencies on Play to load classes

---

scripts/start.sh

It took me a while to figure out how to configure java options so thought I would share this. Also, I think it would be helpful to enable heap dump on OOM by default for future debugging.

Add JAVA_OPTS env var export to start.sh

---

app/com/linkedin/drelephant/security/HadoopSecurity.java
app/com/linkedin/drelephant/util/Utils.java

In order to read the values of JVM properties, -Dkeytab.user and -Dkeytab.location, using System.getProperty(), instead of Play APIs.
Using ClassLoader.getSystemClassLoader().getResourceAsStream to read the config files, instead of Play APIs.
This change is a continuation of a previous change, https://github.com/linkedin/dr-elephant/pull/179
@akshayrai : Can you please review this.

Removes play dependencies to read config file and read system properties.

---

app-conf/SchedulerConf.xml
app/com/linkedin/drelephant/schedulers/NoScheduler.java

Use map-reduce job configuration properties to provide flow and job
history run outside of a scheduler

Scheduler-less support for flow and job history

---

app/com/linkedin/drelephant/analysis/AnalyticJob.java

In the [proposed modularization refactoring design](https://docs.google.com/document/d/191PZZGxt0PMIj7j2Bj4pIPgi_Xuu7HRLYtRkhH9daSg/edit), we want to run analysis driver backend without the fetcher part. The AnalyticJob class current has getAnalysis method that fetches app data on its own. The analysis driver backend cannot use this method.
This change adds a version of the method that takes app data as input. With this, the analysis driver backend will prepopulate app data and call the new method.

Adds a version of analyze method taking app data as input

---

app-conf/HeuristicConf.xml
app/com/linkedin/drelephant/mapreduce/heuristics/DistributedCacheLimitHeuristic.java
app/views/help/mapreduce/helpDistributedCacheLimit.scala.html
test/com/linkedin/drelephant/mapreduce/heuristics/DistributedCacheLimitHeuristicTest.java

Jobs which put large files(> 500MB) in the distributed cache are flagged.
Files as part of the following are considered.
mapreduce.job.cache.files
mapreduce.job.cache.archives

LIHADOOP-23735: Added new heuristic DistributedCacheLimit heuristic.

---

app/com/linkedin/drelephant/mapreduce/data/MapReduceTaskData.java
app/com/linkedin/drelephant/mapreduce/fetchers/MapReduceFSFetcherHadoop2.java
app/com/linkedin/drelephant/mapreduce/fetchers/MapReduceFetcherHadoop2.java
app/com/linkedin/drelephant/mapreduce/heuristics/GenericDataSkewHeuristic.java
app/com/linkedin/drelephant/mapreduce/heuristics/GenericGCHeuristic.java
app/com/linkedin/drelephant/mapreduce/heuristics/GenericMemoryHeuristic.java
app/com/linkedin/drelephant/mapreduce/heuristics/MapperSpeedHeuristic.java
app/com/linkedin/drelephant/mapreduce/heuristics/MapperSpillHeuristic.java
app/com/linkedin/drelephant/mapreduce/heuristics/MapperTimeHeuristic.java
app/com/linkedin/drelephant/mapreduce/heuristics/ReducerTimeHeuristic.java
app/com/linkedin/drelephant/mapreduce/heuristics/ShuffleSortHeuristic.java
test/com/linkedin/drelephant/analysis/AnalyticJobTest.java
test/com/linkedin/drelephant/mapreduce/TestTaskLevelAggregatedMetrics.java
test/com/linkedin/drelephant/mapreduce/heuristics/JobQueueLimitHeuristicTest.java
test/com/linkedin/drelephant/mapreduce/heuristics/MapperDataSkewHeuristicTest.java
test/com/linkedin/drelephant/mapreduce/heuristics/MapperGCHeuristicTest.java
test/com/linkedin/drelephant/mapreduce/heuristics/MapperMemoryHeuristicTest.java
test/com/linkedin/drelephant/mapreduce/heuristics/MapperSpeedHeuristicTest.java
test/com/linkedin/drelephant/mapreduce/heuristics/MapperSpillHeuristicTest.java
test/com/linkedin/drelephant/mapreduce/heuristics/MapperTimeHeuristicTest.java
test/com/linkedin/drelephant/mapreduce/heuristics/ReducerDataSkewHeuristicTest.java
test/com/linkedin/drelephant/mapreduce/heuristics/ReducerGCHeuristicTest.java
test/com/linkedin/drelephant/mapreduce/heuristics/ReducerMemoryHeuristicTest.java
test/com/linkedin/drelephant/mapreduce/heuristics/ReducerTimeHeuristicTest.java
test/com/linkedin/drelephant/mapreduce/heuristics/ShuffleSortHeuristicTest.java

As discussed in issue, https://github.com/linkedin/dr-elephant/issues/194, the meaning of sampling is quite confusing in MapReduceTaskData. There are many constructors and setters are used to enable sampling flag in this class, however, it's not clear what is the correct way to enable sampling flag. It's also important to know that the field name,` _sampled`, does not correctly capture the meaning of that field.
In this change, the name of the field is changed to `_isTimeAndCounterDataPresent` to clearly define this field. This change also removes multiple ways to enable this flag. Only one method, `setTimeAndCounter`, can enable this flag, which avoids any confusion. Modified the relevant unit tests.
@paulbramsen, @shankar37, @babak-altiscale, and @akshayrai: Plese review this change. …

Cleanes up MapReduceTaskData class by removing unnecessary constructors

---

app/com/linkedin/drelephant/spark/fetchers/SparkRestClient.scala
test/com/linkedin/drelephant/spark/fetchers/SparkRestClientTest.scala

As mentioned in the issue, https://github.com/linkedin/dr-elephant/issues/175, the current REST API fetcher fails to parse client mode applications because there is no attemptId in REST response of ApplicationInfo. 
In this change, we are modifying the fetcher to not consider attemptId in REST urls when attemptId is not returned by ApplicationInfo response, as it's mentioned in this Spark [documentation](http://spark.apache.org/docs/latest/monitoring.html#rest-api).
With this change, the fetcher will be able to process both Client and Cluster mode applications.
@akshayrai can you please have a look.
Thank you.

Fixes Spark REST fetcher for client mode applications

---

app/com/linkedin/drelephant/mapreduce/fetchers/MapReduceFSFetcherHadoop2.java
project/Dependencies.scala
test/com/linkedin/drelephant/mapreduce/fetchers/MapReduceFSFetcherHadoop2Test.java

For MapReduce jobs with succeeded status but containing failed tasks (by setting mapreduce.map.failures.maxpercent to non zero), MapReduceFSFetcherHadoop2 will construct a task list with null pointers. This PR fixes this bug and adds a unit test to distinguish it.

fix for null pointers in TaskList returned by MapReduceFSFetcherHadoop2

---

app/com/linkedin/drelephant/spark/fetchers/SparkRestClient.scala
test/com/linkedin/drelephant/spark/fetchers/SparkRestClientTest.scala

This change fixes the [issue](https://github.com/linkedin/dr-elephant/issues/216), where Cloudera Manager adds http in their jobhistory webadress. And that causes the failure of SparkFetcher.
@paulbramsen @shankar37 
Please take a look.
Thank you.

Fixes issue caused by http in history server config property

---

app/com/linkedin/drelephant/mapreduce/TaskLevelAggregatedMetrics.java
app/com/linkedin/drelephant/mapreduce/heuristics/JobQueueLimitHeuristic.java
test/com/linkedin/drelephant/mapreduce/TestTaskLevelAggregatedMetrics.java
test/com/linkedin/drelephant/mapreduce/heuristics/JobQueueLimitHeuristicTest.java
test/com/linkedin/drelephant/mapreduce/heuristics/MapperDataSkewHeuristicTest.java
test/com/linkedin/drelephant/mapreduce/heuristics/MapperGCHeuristicTest.java
test/com/linkedin/drelephant/mapreduce/heuristics/MapperMemoryHeuristicTest.java
test/com/linkedin/drelephant/mapreduce/heuristics/MapperSpeedHeuristicTest.java
test/com/linkedin/drelephant/mapreduce/heuristics/MapperSpillHeuristicTest.java
test/com/linkedin/drelephant/mapreduce/heuristics/MapperTimeHeuristicTest.java
test/com/linkedin/drelephant/mapreduce/heuristics/ReducerDataSkewHeuristicTest.java
test/com/linkedin/drelephant/mapreduce/heuristics/ReducerGCHeuristicTest.java
test/com/linkedin/drelephant/mapreduce/heuristics/ReducerMemoryHeuristicTest.java
test/com/linkedin/drelephant/mapreduce/heuristics/ReducerTimeHeuristicTest.java
test/com/linkedin/drelephant/mapreduce/heuristics/ShuffleSortHeuristicTest.java

Also updates all the heuristic unit tests to take non-sampled tasks into account.

Fixes MapReduce aggregator and heuristic to correctly handle task data when sampling is enabled

---

app/com/linkedin/drelephant/spark/data/SparkRestDerivedData.scala
app/com/linkedin/drelephant/spark/fetchers/SparkFetcher.scala
app/com/linkedin/drelephant/spark/fetchers/SparkLogClient.scala
app/com/linkedin/drelephant/spark/fetchers/SparkRestClient.scala
test/com/linkedin/drelephant/spark/SparkMetricsAggregatorTest.scala
test/com/linkedin/drelephant/spark/fetchers/SparkFetcherTest.scala
test/com/linkedin/drelephant/spark/fetchers/SparkRestClientTest.scala
test/com/linkedin/drelephant/spark/heuristics/ExecutorsHeuristicTest.scala
test/com/linkedin/drelephant/spark/heuristics/StagesHeuristicTest.scala
test/com/linkedin/drelephant/util/InfoExtractorTest.java

This PR allows Dr. Elephant to fetch Spark logs without universal
read access to eventLog.dir on HDFS. SparkFetcher would use SparkRestClient
instead of SparkLogClient if configured as
```
<params>
<use_rest_for_eventlogs>true</use_rest_for_eventlogs>
</params>
```
The default behaviour is to fetch the logs via SparkLogClient/WebHDFS.
Closes #199
---
What is missing?

Spark fetcher is now able to fetch event logs via REST API

---

conf/evolutions/default/4.sql

Add an index on yarn_app_result table so the dashboard is display faster.
On our local deployment of dr-elephant with 2 millions of rows in this table(using mariadb) the below request was taking more than 30s:
`select count(*) from yarn_app_result t0 where t0.finish_time > 1496070064837  and t0.severity = 4`
With this index it now takes less than 1s.

Add index on severity, finish_time to speed up welcome page display

---

app-conf/SchedulerConf.xml
app/com/linkedin/drelephant/schedulers/PinballScheduler.java
test/com/linkedin/drelephant/schedulers/PinballSchedulerTest.java

This adds the configuration necessary for the pinball scheduler to be integrated with Dr. Elephant.

add pinball scheduler to dr-elephant

---

app/com/linkedin/drelephant/mapreduce/data/MapReduceCounterData.java
app/com/linkedin/drelephant/mapreduce/heuristics/GenericDataSkewHeuristic.java
app/com/linkedin/drelephant/mapreduce/heuristics/MapperDataSkewHeuristic.java
app/com/linkedin/drelephant/mapreduce/heuristics/MapperSpeedHeuristic.java
app/com/linkedin/drelephant/mapreduce/heuristics/MapperTimeHeuristic.java
app/com/linkedin/drelephant/mapreduce/heuristics/ReducerDataSkewHeuristic.java
test/com/linkedin/drelephant/mapreduce/heuristics/MapperDataSkewHeuristicTest.java
test/com/linkedin/drelephant/mapreduce/heuristics/MapperSpeedHeuristicTest.java
test/com/linkedin/drelephant/mapreduce/heuristics/MapperTimeHeuristicTest.java

Some organizations will use S3 instead of HDFS and currently Dr. Elephant only consider hdfs counters. This adds them here and also updates the heuristics to sum them up. Since there can be s3, s3a, or s3n schemas, it sums them up.

add s3, s3a, s3n bytes read and bytes written, and update heuristics

---

app-conf/SchedulerConf.xml
app/com/linkedin/drelephant/util/Utils.java
app/controllers/Application.java

This change aims at providing a greater flexibility in the way the Flow History and Job History views are displayed. More specifically, it allows to customize the flowtime value (displayed under the _Flow Executions_ column) with a behaviour specific to each scheduler. 
By default, the old behaviour is kept (i.e. filling the flowtime with the job finish time), however, this is now possible to specify, in the scheduler configuration, that this field should be replaced by another one, with a specific formatting.
Concretely, this use case arose when integrating our internal scheduler to Dr.Elephant. Our scheduler is based on the notion of time series, where the _flowExecId_ value (coming from the scheduler) corresponds to the functional date (i.e. the date corresponding to the data partition …

Add custom flowtime per scheduler

---

app/controllers/Application.java
app/views/page/searchPage.scala.html
app/views/results/flowDefinitionIdDetails.scala.html
public/js/searchform.js

This change provides a new way of filtering when doing a search in the Search tab. It is now possible to use the Job Definition ID to get all execution of map reduce jobs that are related to this job definition id.
The results will be grouped by the flow execution id in which the job was executed. When searching with the job definition ID, it will thus be something like this : 
Flow Id: flow_in_which_the_job_is_defined
Flow Execution ID: flow_exec_1
mr_job_triggered_by_the_job_definition_id_1
mr_job_triggered_by_the_job_definition_id_2
...
Flow Execution ID: flow_exec_2
mr_job_triggered_by_the_job_definition_id_1
mr_job_triggered_by_the_job_definition_id_2
...
...

Add filtering on Job Definition Id in the Search view

---

app/views/page/flowHistoryPage.scala.html
app/views/page/jobHistoryPage.scala.html
app/views/page/oldFlowHistoryPage.scala.html
app/views/page/oldJobHistoryPage.scala.html

This aims at fixing the Job History and Flow History views, when searching with _Flow Definition URL/ID_ that are composed of more than one word. Currently, if you search with, for example, a flow definition id such as **core-datamart (prod)**, the search is correctly done, but the string in the text box is sliced, and becomes **core-datamart**. This is an issue, as if you now change the filter for example, switching it from Resources to Time, the search will fail.

Fix text box for ids composed of several words

---

app/com/linkedin/drelephant/analysis/AnalyticJobGeneratorHadoop2.java

Updating AnalyticJobGeneratorHadoop2.java to resolve the Job listing Conflict as per #301
Issues was raised earlier on https://groups.google.com/forum/#!topic/dr-elephant-users/JeIfb-eiT7w

BUGFIX Updating AnalyticJobGeneratorHadoop2.java to resolve the Job listing Conflict

---

app-conf/elephant.conf

Contains fixes mentioned in #297.
1. Adding `jvm_args` instead of `jvm_props` to enable Java Arguments
2. Adding `-mem 1024` to enable default Heap allocation of 1GB.
3. Adding `-J-Xloggc:$project_root../logs/elephant/dr-gc.`date +'%Y%m%d%H%M'` -J-XX:+PrintGCDetails` to enable GC logging in the same directory of Dr. Elephant Logs

BUGFIX Updating java_agrs to elephant.conf for resolving argument conflicts

---

app-conf/FetcherConf.xml

Updating `FetcherConf.xml` to use `MapReduceFSFetcherHadoop` by default for improving performance
Using `MapReduceFSFetcherHadoop` increases the performance ~100 times with the amount of time required for processing and number of jobs processed in a minute.
With the original `MapReduceFetcherHadoop` class in a Production Cluster , there is a lot of lag in using it, as the number of applications to be processed are very high.

TUNING Updating default MR fetcher for performance

---

app/com/linkedin/drelephant/mapreduce/fetchers/MapReduceFSFetcherHadoop2.java

At peak loads, we observed that the migration of JHS files from intermediate to finished directory gets delayed. In such cases, Dr. Elephant needs to look into the intermediate files and analyze the jobs. However, there is a bug in Dr. Elephant that causes jobs to be skipped due to a missing hdfs directory check.
Added a simple missing hdfs finished directory check. `_fs.exists(new Path(jobHistoryDirPath)`

Dr. Elephant should check for finished directory before listing

---

app/com/linkedin/drelephant/ElephantRunner.java
app/com/linkedin/drelephant/analysis/AnalyticJob.java
app/com/linkedin/drelephant/analysis/AnalyticJobGenerator.java
app/com/linkedin/drelephant/analysis/AnalyticJobGeneratorHadoop2.java
app/controllers/MetricsController.java

Added logic for making a new retry queue in where jobs are added if the data for these jobs is not fetched within 3 retries of one minute each. 
It basically gives a job more time to fetch data before skipping it.

second retry queue

---

app/com/linkedin/drelephant/spark/fetchers/statusapiv1/StageStatus.java
app/com/linkedin/drelephant/spark/fetchers/statusapiv1/statusapiv1.scala
app/com/linkedin/drelephant/spark/heuristics/ConfigurationHeuristic.scala
app/com/linkedin/drelephant/spark/heuristics/StagesHeuristic.scala
app/com/linkedin/drelephant/spark/legacydata/LegacyDataConverters.scala
app/com/linkedin/drelephant/util/SparkUtils.scala
app/views/help/spark/helpConfigurationHeuristic.scala.html
test/com/linkedin/drelephant/spark/fetchers/SparkRestClientTest.scala
test/com/linkedin/drelephant/spark/heuristics/ConfigurationHeuristicTest.scala
test/com/linkedin/drelephant/spark/heuristics/StagesHeuristicTest.scala
test/com/linkedin/drelephant/spark/legacydata/LegacyDataConvertersTest.scala
test/com/linkedin/drelephant/util/SparkUtilsTest.scala

A threshold is set for executor/driver memory and if the application is using more memory than normal for a Spark application running on the cluster then the users are warned. 
The executor/driver cores are also checked to avoid unreasonable numbers.

Configuration Threshold Heuristic

---

app-conf/FetcherConf.xml
app-conf/HeuristicConf.xml
app/com/linkedin/drelephant/spark/fetchers/statusapiv1/statusapiv1.scala
app/com/linkedin/drelephant/spark/heuristics/JvmUsedMemoryHeuristic.scala
app/com/linkedin/drelephant/spark/legacydata/LegacyDataConverters.scala
app/views/help/spark/helpJvmUsedMemoryHeuristic.scala.html
test/com/linkedin/drelephant/spark/SparkMetricsAggregatorTest.scala
test/com/linkedin/drelephant/spark/heuristics/ExecutorGcHeuristicTest.scala
test/com/linkedin/drelephant/spark/heuristics/ExecutorsHeuristicTest.scala
test/com/linkedin/drelephant/spark/heuristics/JvmUsedMemoryHeuristicTest.scala

To calculate if the executor memory is set to a good value, the average (or median) and maximum peak JVM used memory for executors is examined. Information about each executor’s peak JVM used memory will be available from the executors REST API, in maxPeakJvmUsedMemory.peakJvmUsedMemory. To avoid wasted memory, its checked that the peak JVM used memory is reasonably close to the allocated executor memory, spark.executor.memory -- if it is much smaller, then executor memory can be reduced.

Peak JVM used memory heuristic - (Depends on Custom SHS - Requires peakJvmUsedMemory metric)

---

app-conf/HeuristicConf.xml
app/com/linkedin/drelephant/spark/fetchers/statusapiv1/statusapiv1.scala
app/com/linkedin/drelephant/spark/heuristics/UnifiedMemoryHeuristic.scala
app/com/linkedin/drelephant/spark/legacydata/LegacyDataConverters.scala
app/views/help/spark/helpUnifiedMemoryHeuristic.scala.html
test/com/linkedin/drelephant/spark/SparkMetricsAggregatorTest.scala
test/com/linkedin/drelephant/spark/heuristics/ExecutorGcHeuristicTest.scala
test/com/linkedin/drelephant/spark/heuristics/ExecutorStorageSpillHeuristicTest.scala
test/com/linkedin/drelephant/spark/heuristics/ExecutorsHeuristicTest.scala
test/com/linkedin/drelephant/spark/heuristics/JvmUsedMemoryHeuristicTest.scala
test/com/linkedin/drelephant/spark/heuristics/StagesHeuristicTest.scala
test/com/linkedin/drelephant/spark/heuristics/UnifiedMemoryHeuristicTest.scala
test/com/linkedin/drelephant/util/SparkUtilsTest.scala

The amount of unified memory can be examined to see if spark.memory.fraction can be adjusted. If the ratio of unified memory to executor memory is much smaller than  spark.memory.fraction, then more memory has been reserved for execution than is being used. This memory can instead be allocated for user memory, and/or total executor memory could be reduced.

Peak Unified Memory Heuristic - (Depends on Custom SHS - Requires peakUnifiedMemory metric)

---

app/com/linkedin/drelephant/analysis/HadoopAggregatedData.java
app/com/linkedin/drelephant/spark/SparkMetricsAggregator.scala
app/com/linkedin/drelephant/spark/legacydata/LegacyDataConverters.scala
test/com/linkedin/drelephant/spark/SparkMetricsAggregatorTest.scala

Fixed the calculation of resources used/wastage, now the resources used is calculated by summing up the resources used by each executor as opposed to before where the executors were assumed to use the entire memory allocated for them. The resources allocated for use is also calculated by multiplying the time spent by each executor with the total memory allocated for an executor, and then summing them up.

Fixed resources used/wasted computation for spark jobs - (Depends on Custom SHS - Requires peakJvmUsedMemory metric)

---

app-conf/FetcherConf.xml
app-conf/HeuristicConf.xml
app/com/linkedin/drelephant/spark/fetchers/SparkRestClient.scala
app/com/linkedin/drelephant/spark/heuristics/ConfigurationHeuristic.scala
app/com/linkedin/drelephant/spark/heuristics/DriverHeuristic.scala
app/com/linkedin/drelephant/spark/heuristics/ExecutorGcHeuristic.scala
app/com/linkedin/drelephant/spark/heuristics/ExecutorStorageSpillHeuristic.scala
app/com/linkedin/drelephant/spark/heuristics/ExecutorsHeuristic.scala
app/com/linkedin/drelephant/spark/heuristics/JvmUsedMemoryHeuristic.scala
app/com/linkedin/drelephant/spark/heuristics/StagesHeuristic.scala
app/com/linkedin/drelephant/spark/heuristics/StagesWithFailedTasksHeuristic.scala
app/com/linkedin/drelephant/spark/heuristics/UnifiedMemoryHeuristic.scala
app/com/linkedin/drelephant/util/MemoryFormatUtils.java
app/views/help/spark/helpConfigurationHeuristic.scala.html
app/views/help/spark/helpDriverHeuristic.scala.html
app/views/help/spark/helpJvmUsedMemoryHeuristic.scala.html
app/views/help/spark/helpUnifiedMemoryHeuristic.scala.html
test/com/linkedin/drelephant/spark/fetchers/SparkRestClientTest.scala
test/com/linkedin/drelephant/spark/heuristics/ConfigurationHeuristicTest.scala
test/com/linkedin/drelephant/spark/heuristics/DriverHeuristicTest.scala
test/com/linkedin/drelephant/spark/heuristics/ExecutorGcHeuristicTest.scala
test/com/linkedin/drelephant/spark/heuristics/ExecutorStorageSpillHeuristicTest.scala
test/com/linkedin/drelephant/spark/heuristics/ExecutorsHeuristicTest.scala
test/com/linkedin/drelephant/spark/heuristics/JobsHeuristicTest.scala
test/com/linkedin/drelephant/spark/heuristics/JvmUsedMemoryHeuristicTest.scala
test/com/linkedin/drelephant/spark/heuristics/StagesHeuristicTest.scala
test/com/linkedin/drelephant/spark/heuristics/StagesWithFailedTasksHeuristicTest.scala
test/com/linkedin/drelephant/spark/heuristics/UnifiedMemoryHeuristicTest.scala
test/com/linkedin/drelephant/util/MemoryFormatUtilsTest.java

This PR adds new Spark Heuristics in Dr Elephant. There are several heuristics like:
Executor JVM Memory Heuristic: Checks whether the allocated is much more than the peak JVM used memory
Executor Peak Unified Memory: Checks whether the memory allocated for Unified Memory region is much more than the memory used by it. 
Executor Spill: Checks whether Executor memory is spilled and gives suggestions. 
Executor GC: checks how much time is spent in GC as compared to the total running time of the job.
Driver: checks driver configurations, driver GC time and JVM used memory.
Stages With Failed Tasks: checks for the stages having failed tasks and checks for the error messages of the tasks failed.

Spark Heuristics for Dr. Elephant 

---

app/com/linkedin/drelephant/AutoTuner.java
app/com/linkedin/drelephant/clients/azkaban/AzkabanJobStatusUtil.java
app/com/linkedin/drelephant/clients/azkaban/AzkabanWorkflowClient.java
app/com/linkedin/drelephant/tuning/AzkabanJobCompleteDetector.java

Currently Auto Tuning does not support job execution IDs from different azkaban host and it fails while calling azkaban rest api. This PR have changes to support multiple azkaban host and it also takes care of creating new session every hour for azkaban rest api.

Added support for multiple Azkaban Host URL

---

test/com/linkedin/drelephant/tuning/PSOParamGeneratorTest.java
test/resources/AutoTuningConf.xml
test/rest/RestAPITest.java

Fixed issue: https://github.com/linkedin/dr-elephant/issues/341

Bug fix: Auto tuning disable model unit test failure

---

app/com/linkedin/drelephant/spark/fetchers/SparkFetcher.scala

Reducing time out of spark fetcher from 60 to 5 seconds so that the analytic queue does not wait on response from SHS for Spark Jobs.

reducing time out of spark fetcher from 60 to 5 seconds

---

app/com/linkedin/drelephant/ElephantRunner.java
app/com/linkedin/drelephant/spark/fetchers/SparkFetcher.scala
app/com/linkedin/drelephant/spark/fetchers/SparkRestClient.scala

Changed the usage of async to Future/blocking. Reason being due to the async keyword, it wasn't able to allocate threads to the process and hence, was timing out very frequently. 
The number of concurrently blocking computations can exceed the parallelism level only if each blocking call is wrapped inside a blocking call. Otherwise, there is a risk that the thread pool in the global execution context is starved, and no computation can proceed.
Reference: https://docs.scala-lang.org/overviews/core/futures.html#the-global-execution-context

changed async to future/blocking and changed the error to warn

---

app/com/linkedin/drelephant/spark/fetchers/SparkFetcher.scala
app/com/linkedin/drelephant/spark/fetchers/SparkLogClient.scala
app/com/linkedin/drelephant/spark/fetchers/SparkRestClient.scala

Removing blocking keyword to ensure that a large number of threads are not created if some of the threads are blocked.

Removing blocking keyword 

---

app/com/linkedin/drelephant/ElephantContext.java
app/com/linkedin/drelephant/spark/fetchers/SparkRestClient.scala
app/com/linkedin/drelephant/spark/heuristics/ConfigurationHeuristic.scala
app/com/linkedin/drelephant/spark/heuristics/DriverHeuristic.scala
app/com/linkedin/drelephant/spark/heuristics/ExecutorGcHeuristic.scala
app/com/linkedin/drelephant/spark/heuristics/UnifiedMemoryHeuristic.scala
test/com/linkedin/drelephant/spark/heuristics/ConfigurationHeuristicTest.scala
test/com/linkedin/drelephant/spark/heuristics/ExecutorGcHeuristicTest.scala
test/com/linkedin/drelephant/spark/heuristics/UnifiedMemoryHeuristicTest.scala

**Description**
Making some changes to the current Spark Heuristics for executor GC, configuration , unified memory.
Changes made are as follows::
- Removed the Driver Gc heuristic
- If total executor runtime is less than 5 mins then won't flag for the executor GC heuristic
- If spark.memory.fraction > 0.05 and unified allocated memory > 256 MB then only consider for peak unified memory severity
- Changes in configuration heuristic for spark.executor.core, severity will be NONE if cores <= 4
**How this is tested**
For these changes, tests are included in the respective tests for the heuristics.

Spark heuristic modification

---

app/com/linkedin/drelephant/tuning/AbstractFitnessManager.java
app/com/linkedin/drelephant/tuning/hbt/FitnessManagerHBT.java
app/com/linkedin/drelephant/tuning/obt/FitnessManagerOBTAlgoIPSO.java
app/com/linkedin/drelephant/tuning/obt/FitnessManagerOBTAlgoPSO.java

In this PR changes are made to the query to fetch TuningJobExecutionParamSet in the AbstractFitnessManager method. Earlier it was assumed that there will be unique row for each JobSuggestedParamSet in TuningJobExecutionParamSet, it is fixed in this PR.
**HOW IT IS TESTED**
Testing is done on EI.

Fixing query to fetch latest TuningJobExecutionParamSet

---

app/controllers/Application.java
app/models/TuningJobDefinition.java
conf/evolutions/default/6.sql
conf/routes
test/resources/test-init-baseline.sql
web/app/controllers/job.js
web/app/models/tunein.js
web/app/routes/job.js
web/app/styles/app.css
web/app/templates/job.hbs

In this PR, there are changes made to the TuneIn UI to add some helpful information for the user such as 
- Reason to disable TuneIn for some job
- Contact info in case of any query
There is one significant change to provide a button to the user for requesting to show tuning parameters instead of showing all the parameters directly. After this change UI will look like as below: 
and after request is processed all the tuning recommendations will be visible to the user
**How This is Tested**
Testing is done on the EI.

Making changes to TuneIn recommendation UI for adding more information

---

app/com/linkedin/drelephant/tuning/AutoTuningAPIHelper.java

In this PR the changes are made to fix the bug due to race condition while adding flow execution details in the Flow Execution table. This is achieved by using the synchronized keyword for  getFlowExecution method.

Making getFlowExecution synchronized block to avoid the race condition

---

.travis.yml

JDK 7 builds for Dr.Elephant fail in Travis CI because oraclejdk7 support is no longer available after corresponding build machines were updated to Ubuntu Trusty.
Use openjdk7 instead.

openjdk7 support for Travis CI

---

baseline.conf
build.sbt
common.sh
compile.sh
cpd.sbt
project/plugins.sbt
travis.sh

CPD or Copy Paste Detector is part of PMD which is a source code analyzer tool. CPD is useful in detecting duplicate code. Duplicate code while not desirable can also be a nightmare for code maintainability as same changes may have to be replicated across multiple areas of code. Dr.Elephant too has a fair bit of code duplication and we would want to not allow that. In some cases, upto 70-80 lines are duplicated. This PR is for integration of CPD into Dr.Elephant.
**This PR does the following:**
1. Integrate cpd4sbt plugin into Dr.Elephant to invoke CPD.
2. Make necessary changes in travis.sh script so that CPD runs for both Java and Scala code. As such CPD settings only allow one language to be configured. While running CI build, we first run CPD for Java and then modify cpd.sbt(file for …

Integrate CPD into Dr.Elephant for detecting code duplication

---

app/com/linkedin/drelephant/analysis/AnalyticJobGeneratorHadoop2.java
test/com/linkedin/drelephant/analysis/AnalyticJobGeneratorHadoop2Test.java

Operations on second retry queue for jobs in Dr Elephant are not thread safe.
In AnalyticJobGeneratorHadoop2#fetchAnalyticJobs, we iterate over the jobs in second retry queue and if the job is eligible for retry, remove it from the queue while iterating over it.
But while that's happening, another thread, which is processing the job, on failure, can also add to the same queue by calling AnalyticJobGeneratorHadoop2#addIntoSecondRetryQueue.
This can lead to concurrent modification exception.

Operations on second retry queue for jobs in Dr Elephant are not thread safe

---

app/controllers/MetricsController.java
test/common/TestConstants.java
test/controllers/MetricsControllerTest.java

Second retry queue size is currently not exposed as a metric from /metrics endpoint in Dr.Elephant.
It's useful to know how many jobs are stuck in this queue. As there is exponential backoff retry for jobs in the second retry queue, a high value for this metric may indicate a major issue and jobs would face considerable delay. Jobs will go into second retry queue primarily when Spark History Server is overloaded.

Expose second retry queue size as a metric in Dr.Elephant

---

app/com/linkedin/drelephant/tuning/engine/SparkHBTParamRecommender.java
app/com/linkedin/drelephant/tuning/obt/ParameterGenerateManagerOBTAlgoPSOIPSOImpl.java
app/controllers/Application.java
test/com/linkedin/drelephant/tuning/TuningManagerTest.java

- Adding try-catch block for reading counters
- Making change for deciding tuning algorithm based on job type
- In case of IPSO PSO, making a change to not generate parameter unless auto_apply=1 for the job

Fixes for Pig tuning

---

app/com/linkedin/drelephant/tez/TezMetricsAggregator.java

When DrElephant analyze Pig job running on TEZ, all metrics are wrong.
My JobTypeConf.xml for tez is:
```xml
<jobType>
<name>HiveTez</name>
<applicationtype>tez</applicationtype>
<conf>hive.mapred.mode</conf>
<isDefault/>
</jobType>
<jobType>
<name>TezPig</name>
<applicationtype>tez</applicationtype>
<conf>pig.script</conf>
</jobType>
```
After some diggings, I found that in the methods getMapContainerSize and getReducerContainerSize,  line 88 and 100 always throw NumberFormatException when DrElephant analyze a Pig job.
https://github.com/linkedin/dr-elephant/blob/44419ed7036f55d30d32e6af46871993f0918055/app/com/linkedin/drelephant/tez/TezMetricsAggregator.java#L86-L96
https://github.com/linkedin/dr-elephant/blob/44419ed7036f55d30d32e6af46871993f0918055/app/com/linkedin/drelephant/tez/TezM …

Fix wrong metrics for Pig job using TEZ

---

app-conf/HeuristicConf.xml
app/com/linkedin/drelephant/AutoTuner.java
app/com/linkedin/drelephant/spark/SparkMetricsAggregator.scala
app/com/linkedin/drelephant/spark/fetchers/statusapiv1/statusapiv1.scala
app/com/linkedin/drelephant/spark/heuristics/SparkApplicationMetricsHeuristic.scala
app/com/linkedin/drelephant/spark/legacydata/LegacyDataConverters.scala
app/com/linkedin/drelephant/spark/legacydata/SparkExecutorData.java
app/com/linkedin/drelephant/tuning/AbstractFitnessManager.java
app/com/linkedin/drelephant/tuning/hbt/FitnessManagerHBT.java
app/com/linkedin/drelephant/tuning/obt/FitnessManagerOBT.java
app/models/AppResult.java
app/views/help/spark/helpApplicationMetricsHeuristic.scala.html
test/com/linkedin/drelephant/spark/SparkMetricsAggregatorTest.scala
test/com/linkedin/drelephant/spark/heuristics/DriverHeuristicTest.scala
test/com/linkedin/drelephant/spark/heuristics/ExecutorGcHeuristicTest.scala
test/com/linkedin/drelephant/spark/heuristics/ExecutorStorageSpillHeuristicTest.scala
test/com/linkedin/drelephant/spark/heuristics/ExecutorsHeuristicTest.scala
test/com/linkedin/drelephant/spark/heuristics/JvmUsedMemoryHeuristicTest.scala
test/com/linkedin/drelephant/spark/heuristics/SparkApplicationMetricsHeuristicTest.scala
test/com/linkedin/drelephant/spark/heuristics/SparkTestUtilities.scala
test/com/linkedin/drelephant/spark/heuristics/UnifiedMemoryHeuristicTest.scala

Changes in this PR:
**Adding a new Heuristic Spark Application Heuristic** 
This heuristic is an informational heuristic. and contains following metrics. 
- Total Input Data Size
- Total Input Records,
- Total Output Data Size
- Total Shuffle Read and Write Bytes
- Total Shuffle Read and Write Records,
- Total Memory Bytes Spilled
- Total Disk Bytes Spilled
**Making changes to use total input data size available for fitness computation of Spark jobs**
Using total input data size from above heuristic in fitness computation of Spark jobs. 
**Change in computation for resource usage and resource wastage**
Currently we use total_duration from executor metrics and executor memory to compute resource usage. Total duration is actually based on total core. If for an executor, number of core is 2 …

Spark Application Heuristic, resource usage computation, fitness computation fixes

---

app-conf/elephant.conf
app/com/linkedin/drelephant/ElephantContext.java
app/com/linkedin/drelephant/analysis/AnalyticJobGeneratorHadoop2.java

This change is to add filter in RM application fetch API call. Now users can configure if they want to apply any filters for processing applications. This need to configured in elephant.conf. 
Example: 
rm_application_filter="applicationTags=tag1&user=user1&applicationType=SPARK
Above filter will process application containing applicationTags "tag1" and from "user1" with application type as "SPARK". 
Done testing with trying different filters and with no filters.

RM application filter changes

---

web/app/components/tunein-info.js
web/app/helpers/or.js
web/app/routes/job.js
web/app/templates/components/tunein-info.hbs
web/app/templates/job.hbs
web/tests/integration/components/tunein-info-test.js
web/tests/unit/helpers/or-test.js

In this PR the changes are made to the TuneIn's current UI structure. As of now, TuneIn's UI template is part of the Dr.Elephant job page template. Since TuneIn details have their own variables which need to be refreshed on any transition, so it required for TuneIn UI to have their own component. This will help in better management of the variables and also makes it easier to reuse the template for TuneIn in the future if required.
Some refactoring is also done in the TuneIn UI, such as:
- The condition to check if all the heuristics passed is modified. After this change, TuneIn will show all the heuristics passed when the overall Severity will be None or Low instead showing when overall Heuristic is only None.

Using a seperate Ember component for TuneIn details

---

app-conf/AutoTuningConf.xml
app/com/linkedin/drelephant/AutoTuner.java
app/com/linkedin/drelephant/DrElephant.java
app/com/linkedin/drelephant/tuning/TuningPerformanceReportManager.java
app/com/linkedin/drelephant/tuning/TuningWhiteListingManager.java
app/com/linkedin/drelephant/util/ProcessUtil.java
compile.sh
conf/evolutions/default/8.sql
scripts/azkaban_job_whitelisting_blacklisting.py
scripts/mysql_config.json
scripts/start.sh
scripts/tuning_performance_reports.py

This change contains script for whitelisting and blacklisting Azkaban projects for auto tuning. With this user can whitelist or blacklist few projects, flows and jobs using expressions. Once a project is whitelisted, then all jobs for that project which matches expressions given in flow_name_expr and job_name_expr will be enabled for auto tuning. (auto_apply flag enabled). Same way blacklisted jobs will be disabled for auto tuning. 
We can configure rules, which will contain following information:
-   `rule_type` enum('WHITELIST','BLACKLIST') - 'Type of the rule, whitelist or blacklist',
-   `project_name`-  'Azkaban Project Name to be whitelisted',
-   `flow_name_expr` -  'flow name regular expression for whitelist/blacklist',
-   `job_name_expr` -  'job name regular expression for …

Azkaban Job Whitelisting Blacklisting for Auto Tuning

---

app/com/linkedin/drelephant/tuning/AbstractJobStatusManager.java
app/com/linkedin/drelephant/tuning/hbt/FitnessManagerHBT.java
test/com/linkedin/drelephant/tuning/JobStatusManagerTestRunner.java

Adding a try catch block for database update step, so if there is any failure in database update it should continue updating left over rows.

Adding a try catch block to make sure thread continue

---

web/app/routes/job.js
web/app/services/session.js

Currently the username of the active user is saved as an attribute of `Session` service, but the problem is that on the browser refresh the attributes of the service are flushed so on further attempts to update the TuneIn parameters, the username is null. To resolve this we need to persist the username in the HTML local storage which will persist the username even after the page refresh/reload.

Persisting the active user's details in HTML local storage

---

app/com/linkedin/drelephant/tuning/alerting/NotificationDataGenerator.java
test/com/linkedin/drelephant/tuning/AlertingTest.java

This PR is to 
1) Add recency window to Best Parameter Penalty rule , so that developers don't get old notification.
2) Also to add Job definition Id to notification, so that developers knows from which cluster notification are coming
3) Disable users notification .
Testing
Unit test cases are modified to test the code

Adding recency window in rule and disabling user notification

---

.gitignore
app-conf/HeuristicConf.xml
app-conf/JobTypeConf.xml
app/com/linkedin/drelephant/tony/data/TonyApplicationData.java
app/com/linkedin/drelephant/tony/fetchers/TonyFetcher.java
app/com/linkedin/drelephant/tony/heuristics/TaskMemoryHeuristic.java
compile.sh
test/resources/JobTypeConf.xml

This is just skeleton code with hardcoded values just to plumb through support for TonY jobtype. I now see it in my local Dr. Elephant instance:
In follow-up PRs, I will add a proper implementation.
Please ignore commented-out code for now.
I plan to do incremental PRs and merge them into the `tony-fetcher` branch and once support for TonY jobtype is complete, I will send a PR for merging `tony-fetcher` into `master`.

Skeleton code for TonY jobtype support in Dr. Elephant #553

---

app-conf/HeuristicConf.xml
app/com/linkedin/drelephant/analysis/HeuristicResult.java
app/com/linkedin/drelephant/tony/data/TonyApplicationData.java
app/com/linkedin/drelephant/tony/heuristics/TaskMemoryHeuristic.java
project/Dependencies.scala
test/com/linkedin/drelephant/tony/fetchers/TonyFetcherTest.java
test/com/linkedin/drelephant/tony/heuristics/TaskMemoryHeuristicTest.java

* Added a max memory heuristic that does the following: for each task type, compares the max memory used by any of the tasks and compares it against some thresholds. The severity returned is the highest severity across all task types.
* The heuristic will include number of tasks, requested memory, and max memory for each task type.
* If the requested memory for a task type is <= the default container size, severity is NONE for that task type
* The default container size is 2 GB. The default thresholds are 0.5 for CRITICAL, 0.6 for SEVERE, 0.7 for MODERATE, and 0.8 for LOW. If (max memory / requested memory) > 0.8, severity is NONE.
* Added unit tests.

Implement TonY TaskMemoryHeuristic

---

app/com/linkedin/drelephant/exceptions/azkaban/AzkabanJobLogAnalyzer.java
app/controllers/api/v1/Web.java

Currently, Exception Fingerprinting for MapReduce is not working due to the modified Azkaban logs statements at the end of the job. In this PR, changes are made to update the regex patterns for analyzing Azkaban logs.
**TESTING**
Tested changes in the EI instance.
Before the changes: 
After Changes:

Fix for the MapReduce Exception Fingerprinting

---

.gitignore
app/com/linkedin/drelephant/tony/TonyMetricsAggregator.java
app/com/linkedin/drelephant/tony/fetchers/TonyFetcher.java
app/com/linkedin/drelephant/tony/heuristics/TaskMemoryHeuristic.java
app/com/linkedin/drelephant/tony/util/TonyUtils.java
compile.sh

* Fixed NPE when no metrics (The `ProcfsBasedProcessTree` that TonY uses only works on Mac but not Linux, so when running TonY on Mac, there are no memory metrics.)
* Updated logic so even when there are no metrics, we still print info like number of worker tasks and memory requested per worker task.

Fix NPE bug and print task information even when no metrics

---

.gitignore
.travis.yml
app-conf/AggregatorConf.xml
app-conf/FetcherConf.xml
app-conf/HeuristicConf.xml
app-conf/JobTypeConf.xml
app/com/linkedin/drelephant/analysis/HeuristicResult.java
app/com/linkedin/drelephant/mapreduce/TaskLevelAggregatedMetrics.java
app/com/linkedin/drelephant/tony/TonyMetricsAggregator.java
app/com/linkedin/drelephant/tony/data/TonyApplicationData.java
app/com/linkedin/drelephant/tony/data/TonyTaskData.java
app/com/linkedin/drelephant/tony/fetchers/TonyFetcher.java
app/com/linkedin/drelephant/tony/heuristics/TaskMemoryHeuristic.java
app/com/linkedin/drelephant/tony/util/TonyUtils.java
app/models/AppResult.java
app/views/help/tony/helpTaskMemory.scala.html
build.sbt
compile.sh
project/Dependencies.scala
project/checkstyle-config.xml
project/checkstyle-java.header
test/com/linkedin/drelephant/tony/TonyMetricsAggregatorTest.java
test/com/linkedin/drelephant/tony/fetchers/TonyFetcherTest.java
test/com/linkedin/drelephant/tony/heuristics/TaskMemoryHeuristicTest.java
test/resources/JobTypeConf.xml

* Implemented `TonyFetcher`, `TaskMemoryHeuristic`, `TonyMetricsAggregator`.
* Added unit tests for each.
* Disabled `TonyFetcher` by default in the included `FetcherConf.xml`.
* Bumped source and target JDK versions to 1.8 since TonY requires that.
Please ignore the "Unknown" max memory, as that is due to the `ProcfsBasedProcessTree` that TonY uses only working on Linux, not Mac. On a Linux machine, max memory metrics are collected and emitted.

Fix #553: Add support for TonY jobs

---

app/com/linkedin/drelephant/tuning/hbt/ParameterGenerateManagerHBT.java

In this PR changes are made to remove the usage of NOT_STARTED ExecutionState as this is sort of redundant and the main reason for removing this as the team decided to use this ExecutionState type for an upcoming hotfix. For that hotfix to work this ExecutionState type cannot be used anywhere else.

Removing code with usage of NOT_STARTED ExecutionState

---

project/plugins.sbt

This PR contains changes to address the issue raised in the ticket PWN-17653(internal ticket). The changes are made to use HTTPS enabled sbt dependency resolver so that we only download dependency JARs on a secure connection.

Using HTTPS enabled sbt repo URL for dependency resolution

---

app/com/linkedin/drelephant/tuning/engine/SparkHBTParamRecommender.java

Seeing few failures in new parameter suggestion. Adding a buffer of 100 MB per core.

Adding more buffer for executor memory

---

app/controllers/Application.java
app/controllers/api/v1/JsonKeys.java

In this PR the changes are made to handle the case where show_recommendation_count is NULL and TuneIn API needs to increment on every view. MySql DB is not accepting the DEFAULT value of zero which was mentioned while creating the respective column in TuningJobDefinition table.

Fix the case where showRecommendation is NULL due to MySql settings

---

app/com/linkedin/drelephant/tony/heuristics/TaskMemoryHeuristic.java
test/com/linkedin/drelephant/tony/heuristics/TaskMemoryHeuristicTest.java

Now if user requests 3 GB and actual memory usage is 2.01 GB, Dr. Elephant will still give a pass, since reducing request memory (1 GB units) would lead to OOM.
Also now set a score for TaskMemoryHeuristic, which downstream applications might use for evaluating whether a workflow can run in production.

Fix #599, #600: Set score for TaskMemoryHeuristic, allow for grace memory headroom

---

app/com/linkedin/drelephant/tuning/hbt/AutoTuningFailureHandler.java

While recalculating best parameters, it sets the best parameter for which fitness is maximum. But we need to set minimum fitness parameter as the best parameter.

Bug fix while calculating best parameter for retired jobs

---

app/com/linkedin/drelephant/clients/azkaban/AzkabanWorkflowClient.java

This change contains the fix for a BUG which was caused by a change in PR#623. Due to this bug the job status of the job was not updating accordingly and because of that TuneIn was impacted. The problem was that the WorkflowClient will fetch job info only once. Resolved this by removing the condition for checking if the job info is fetch earlier.
**HOW THIS CHANGE IS TESTED**
Have done the EndToEnd testing.

Fixing the bug with the job status update

---

app/com/linkedin/drelephant/analysis/AnalyticJob.java
app/com/linkedin/drelephant/analysis/AnalyticJobGeneratorHadoop2.java
app/com/linkedin/drelephant/spark/SparkMetricsAggregator.scala
app/com/linkedin/drelephant/spark/fetchers/statusapiv1/statusapiv1.scala
app/com/linkedin/drelephant/spark/legacydata/LegacyDataConverters.scala
app/com/linkedin/drelephant/spark/legacydata/SparkExecutorData.java
app/org/apache/spark/deploy/history/SparkDataCollection.scala
test/com/linkedin/drelephant/spark/SparkMetricsAggregatorTest.scala
test/com/linkedin/drelephant/spark/heuristics/DriverHeuristicTest.scala
test/com/linkedin/drelephant/spark/heuristics/ExecutorGcHeuristicTest.scala
test/com/linkedin/drelephant/spark/heuristics/ExecutorStorageSpillHeuristicTest.scala
test/com/linkedin/drelephant/spark/heuristics/ExecutorsHeuristicTest.scala
test/com/linkedin/drelephant/spark/heuristics/JvmUsedMemoryHeuristicTest.scala
test/com/linkedin/drelephant/spark/heuristics/SparkTestUtilities.scala
test/com/linkedin/drelephant/spark/heuristics/UnifiedMemoryHeuristicTest.scala

Resource usage for Spark jobs in Dr. Elephant is understated. Goal is to fix this, so it represent actual resource usage for a job. 
We found that Dr. Elephant is using total_duration from containers SHS API (Spark History Server), but value, it is getting is total task time instead of duration. Total task time is time, a container spent in working on the tasks. So if a container is live for 10 minutes but it was working on task only for 2 minutes, then spark SHS API returns 2 minutes for total duration. Because of this Dr. Elephant RU numbers for Spark jobs is always less than RMAppSummary data.
To fix this we are making following changes: 
- For resource allocated value, we will use memoryseconds from RM API 
- Start using addTime and removeTime to compute the duration rather than using …

LIHADOOP-48670: Fixing Resource Usage Computation for Spark

---

app/com/linkedin/drelephant/tuning/TuningHelper.java
app/com/linkedin/drelephant/tuning/alerting/NotificationDataGenerator.java
app/com/linkedin/drelephant/tuning/hbt/FitnessManagerHBT.java
test/com/linkedin/drelephant/tuning/AlertingTest.java
test/com/linkedin/drelephant/tuning/TuningManagerTest.java
test/com/linkedin/drelephant/tuning/hbt/FitnessManagerHBTTest.java
test/resources/AutoTuningConf.xml
test/resources/test-param-generate-data.sql

This PR contains the following changes:
1. If a PIG job execution is retried & parameter set in this execution is retried >=2 times then set the flag auto tuning fault to true in job execution. This way this job execution gets alerted and the parameter set gets penalized. Due to the unavailability of exception fingerprinting for PIG, this is a very elementary approach to alert PIG jobs.
2. Developers are alerted if a parameter set is in the "EXECUTED" state for the last 2 days.

Changes to alert PIG jobs and an extra rule in alerting

---

app/com/linkedin/drelephant/spark/data/SparkApplicationData.scala
app/com/linkedin/drelephant/spark/data/SparkRestDerivedData.scala
app/com/linkedin/drelephant/spark/fetchers/SparkFetcher.scala
app/com/linkedin/drelephant/spark/fetchers/SparkRestClient.scala
app/com/linkedin/drelephant/spark/fetchers/statusapiv1/statusapiv1.scala
test/com/linkedin/drelephant/spark/fetchers/SparkRestClientTest.scala

This change is for using spark environment API for getting Spark job configuration. Currently Dr. Elephant uses logs or rest api for logs and then parses that log. We have encountered following issues in the current implementation:
- It only parses LZO4 log files. Many a times people uses other compression formats. In those cases Dr. Elephant fails to analyse those jobs.  
- If there is any failure on the driver side, Dr. Elephant is not able to fetch the logs because of the state of the job. Because of that it fails to analyse the job. 
Spark history server has an environment API, which returns all the configurations. 
Tests Done: 
Compared configurations for many of the analysed jobs with old and new code. There was no difference.

Spark environment api

---

app/com/linkedin/drelephant/tony/heuristics/TaskGPUHeuristic.java

This PR contains changes to fix the drop of TonY application due to NPE caused by unchecked call **get** method of a Map for respective taskType's size.

Fixing NPE caused due to unchecked call to get method of Map

---

app-conf/elephant.conf
scripts/start.sh

This PR contains changes to adding support to Enable SSL for Dr.Elephant given the user has verified certificate and other configs needed. The config needed to enable SSL are present in elephant.conf and should be un-commented to enable SSL. This will help in increasing security for Dr.Elephant and also would make Dr.Elephant to be contacted by other secure services/apps. 
**HOW THESE CHANGES ARE TESTED**
Tested these changes on the local machine with a self-signed certificate and also tested it on EI environment with a CA certified certificate.

Adding support to enable SSL for Dr.Elephant

---

app/com/linkedin/drelephant/exceptions/core/ExceptionFingerprintingSpark.java

Dr Elephant UI only shows the value of column exceptionStackTrace and does not show the Exception Name. 
Hence appending the ExceptionName with ExceptionStackTrace for exception fingerprinting in spark.

Adding ExceptionName with ExceptionStackTrace for Spark Jobs

---

app/com/linkedin/drelephant/spark/fetchers/SparkRestClient.scala

Changing logger level to warn for error in getting job data from Spark Monitoring REST API.

Changing logger level to warn for error in getting job data from Spark Rest Client

---

app/com/linkedin/drelephant/analysis/AnalyticJob.java
app/com/linkedin/drelephant/analysis/AnalyticJobGeneratorHadoop2.java
app/com/linkedin/drelephant/spark/fetchers/SparkFetcher.scala
app/com/linkedin/drelephant/spark/fetchers/SparkRestClient.scala
test/com/linkedin/drelephant/spark/fetchers/SparkFetcherTest.scala

This PR contains the changes to increase the timeout for REST calls to SHS for fetching application data. The reason for making this change is the spike in the number of jobs drop. This change is for done to handle the condition for a short period of time, as the rollout of Incremental Log Parsing by Spark team will enable the SHS to scale by itself.
**HOW CHANGES ARE TESTED**
The changes are tested on test instance against the jobs on the respective cluster.

Increasing the timeout for REST call to Spark History Server

---

project/build.properties

There are several issues that report compilation errors with a message like:
[error] impossible to get artifacts when data has not been loaded. IvyNode = com.fasterxml.jackson.core#jackson-databind;2.5.4
java.lang.IllegalStateException: impossible to get artifacts when data has not been loaded. IvyNode = com.fasterxml.jackson.core#jackson-databind;2.5.4
Examples:
- https://github.com/linkedin/dr-elephant/issues/201
- https://github.com/linkedin/dr-elephant/issues/339
- https://github.com/linkedin/dr-elephant/issues/367
- https://github.com/linkedin/dr-elephant/issues/419
- https://github.com/linkedin/dr-elephant/issues/658
It looks like this message stems from a bug in Ivy which has since been fixed
(https://github.com/sbt/sbt/issues/1598). I'm guessing the fix in Ivy is
included in sbt …

Bump sbt version to 0.13.9

---

app/com/linkedin/drelephant/spark/heuristics/ExecutorGcHeuristic.scala
test/com/linkedin/drelephant/spark/heuristics/ExecutorGcHeuristicTest.scala

Spark Executor Memory heuristic and Executor GC Heuristic are kind of contradicting each other. 
GC ratio is the ratio of JVM GC Time and Executor Run Time. When GC ratio is high, Dr Elephant recommends to increase the executor memory. On increasing the spark.executor.memory, the executor memory threshold becomes severe. 
Hence making severity thresholds for Executor GC Heuristics less restrictive by increasing the boundaries for moderate, severe and critical values.

Relaxing Severity Thresholds for Spark Executor GC

---

app/com/linkedin/drelephant/clients/WorkflowClient.java
app/com/linkedin/drelephant/clients/azkaban/AzkabanWorkflowClient.java
app/com/linkedin/drelephant/exceptions/TonYExceptionFingerprinting.java
app/com/linkedin/drelephant/exceptions/azkaban/AzkabanExceptionLogAnalyzer.java
app/com/linkedin/drelephant/exceptions/core/ExceptionFingerprintingRunner.java
app/com/linkedin/drelephant/exceptions/core/ExceptionFingerprintingSpark.java
app/com/linkedin/drelephant/exceptions/util/Constant.java
app/com/linkedin/drelephant/exceptions/util/ExceptionUtils.java
app/com/linkedin/drelephant/util/Utils.java
test/com/linkedin/drelephant/exceptions/azkaban/AzkabanExceptionLogAnalyzerTest.java
test/resources/exception/azkaban/azkabanExceptionLog_1.log.txt

This PR contains changes needed to use and analyze Azkaban logs for a failed job to get the exceptions from Scheduler. This analysis of Azkaban logs is done when none or not much information is available on the Application level. In those cases, Scheduler captures exceptions which can we of value for the users in finding out the Root Cause of job failure.
**HOW THESE CHANGES ARE TESTED**
Respective unit tests are added for the Analyzer class. Also, tested the changes on the EI machine.

Parsing Azkaban job logs for Exception Fingerprinting

---

app/com/linkedin/drelephant/ElephantRunner.java

Instead of logging the Exception type and stack-trace separately, use
`Logger.error(String msg, Throwable t)` to log the message and stack-trace in a
single ERROR entry.
Here's a disposable test whose output illustrates the difference:
```java
import org.apache.commons.lang.exception.ExceptionUtils;
import org.apache.log4j.Logger;
import org.junit.Test;
public class LogTest {
private static final Logger logger = Logger.getLogger(ElephantRunner.class);
Object nullObj = null;
@Test
public void logExceptionGoodWay() {
try {
nullObj.toString();
} catch (Exception e) {
logger.error("Failure in .toString()!", e);
}
}
@Test
public void logExceptionBadWay() {
try {
nullObj.toString();
} catch (Exception e) {
logger.error(e.getMessage());
logger.error(ExceptionUtils.getStackTrace(e));
}
}
}
``` …

Log Exception object directly
