- README.md
- app-conf/elephant.conf
- compile.sh
- project/plugins.sbt
- scripts/start.sh
* Support for running activator
* Rename jvm_props to jvm_args
* Correction in README
> LIHADOOP-18918: Dr. Elephant should support all play versions

- app/com/linkedin/drelephant/ElephantRunner.java
- app/com/linkedin/drelephant/analysis/AnalyticJobGenerator.java
- app/com/linkedin/drelephant/analysis/AnalyticJobGeneratorHadoop2.java
This builds upon #36. This might not be the most elegant solution, so any feedback would be appreciated.
> separate configuration logic from RM address update logic

- build.sbt
Will use the org name to generate the ivy file which is required to push into the artifactory.
> LIHADOOP-20088: Add organization name to Dr. Elephant to generate ivy file

- jacoco.sbt
Generating code coverage report in xml format too. This will be consumed by the product dashboard.
> LIHADOOP-20476: Generate xml reports for code coverage

- app/com/linkedin/drelephant/mapreduce/TaskLevelAggregatedMetrics.java
- app/com/linkedin/drelephant/util/Utils.java
- app/views/tags/aggregatedMetrics.scala.html
- public/js/timegraphtooltiputility.js
- test/com/linkedin/drelephant/util/UtilsTest.java
* Increase space between the resource wasted icon and text
* Remove hours from the runtime
* Modify tooltip to for runtime
* Show runtime and waitime in hh:mm:ss in job history graph
> LIHADOOP-20629 Minor UI fixes for Dr. Elephant

- app-conf/elephant.conf
- app/views/main.scala.html
- public/assets/analytics/track.js
- scripts/start.sh
Made changes so that web analytics of choice can be configured into Dr. Elephant.
By default the feature will be disabled and can be turned on via configuration. Details on usage
is mentioned in the comments section in application.conf file.
> Web analytics for Dr. Elephant.

- app/com/linkedin/drelephant/ElephantRunner.java
- app/controllers/MetricsController.java
Fix the broken histogram metrics. Add new metrics for number of jobs finished in the last 24 hours and job processing time.
@krishnap
> Improved metrics

- web/app/components/heuristic-details-list.js
- web/app/components/loading-panel.js
- web/app/components/single-heuristic-detail.js
- web/app/controllers/job.js
- web/app/controllers/workflow.js
- web/app/models/application.js
- web/app/models/job.js
- web/app/models/workflow.js
- web/app/routes/app.js
- web/app/routes/job.js
- web/app/routes/workflow.js
- web/app/serializers/application.js
- web/app/serializers/job.js
- web/app/serializers/workflow.js
- web/app/styles/app.css
- web/app/styles/partials/loading-panel.css
- web/app/templates/app.hbs
- web/app/templates/components/heuristic-details-list.hbs
- web/app/templates/components/loading-panel.hbs
- web/app/templates/components/single-heuristic-detail.hbs
- web/app/templates/job.hbs
- web/app/templates/workflow.hbs
- web/tests/integration/components/heuristic-details-list-test.js
- web/tests/integration/components/single-heuristic-detail-test.js
**Following tests have been added:**
web/tests/integration/components/heuristic-details-list-test.js
web/tests/integration/components/single-heuristic-detail-test.js
Tests for other components have already been added in #148 
Following pages have been added:
**Workflow page:**
**Job page:** 
**Application page:**
> LIHADOOP-24102 Create Workflow, Job and Application pages in ember

- app/controllers/Application.java
- app/controllers/api/v1/JsonKeys.java
- app/controllers/api/v1/Web.java
- app/views/index.scala.html
- compile.sh
- conf/routes
Other fixes:
* Additional information to workflow, workflow-summaries rest end point
* Added an rest end point for the dashboard summary
> Integration of the ember app with play framework

- app/com/linkedin/drelephant/mapreduce/MapReduceMetricsAggregator.java
- web/app/controllers/search.js
- web/app/helpers/get-percentage.js
- web/app/templates/search.hbs
LIHADOOP-24687 Dr Elephant shows more than 100% waittime for some jobs
LIHADOOP-24688 Dr Elephant shows NAN when the resource usage and resource wasted is zero
LIHADOOP-24695 Dr Elephant should show loading panel on search page
> Multiple fixes:

- app/controllers/Application.java
in the viewflowhistory, the individual jobs of a coordinator action in oozie were not sorted.
> use an ordered map to preserve order of jobs

- app/controllers/api/v1/JsonKeys.java
- app/controllers/api/v1/Web.java
- conf/routes
- web/app/components/search-panel.js
- web/app/components/user-tags.js
- web/app/controllers/user-details.js
- web/app/helpers/get-duration-breakdown.js
- web/app/helpers/get-resource-in-gb-hours-value.js
- web/app/models/user-detail.js
- web/app/router.js
- web/app/routes/user-details.js
- web/app/styles/app.css
- web/app/styles/partials/user-detail.css
- web/app/styles/partials/user-tabs.css
- web/app/styles/partials/user-tags.css
- web/app/templates/components/search-panel.hbs
- web/app/templates/components/user-tags.hbs
- web/app/templates/user-details.hbs
LIHADOOP-20704: Expose rest interface to provide aggregation adn filtering based on username
Other fixes:
Fix for the MetricsAggregator container size default value
Tooltips on search panel
Fix to search by job_*
>     LIHADOOP-25142: Build the user-summary page for Dr. Elephant

- app/com/linkedin/drelephant/security/HadoopSecurity.java
- app/com/linkedin/drelephant/spark/fetchers/SparkLogClient.scala
- app/org/apache/spark/deploy/history/SparkFSFetcher.scala
- build.sbt
* Dr. Elephant occasionally crashes silently without logging anything.
* Updated the version to the last successfully deployed version at Linkedin.
> HadoopSecurity should be a Singleton

- app/com/linkedin/drelephant/spark/fetchers/SparkFetcher.scala
- app/com/linkedin/drelephant/spark/fetchers/SparkLogClient.scala
- app/com/linkedin/drelephant/spark/fetchers/SparkRestClient.scala
Removing blocking keyword so as to prevent a large number of threads being spawned.
> Removing blocking keyword 

- app/com/linkedin/drelephant/spark/fetchers/SparkRestClient.scala
Making REST Calls sequential so that it doesn't put much pressure on the SHS
> making rest calls sequential

- app/views/main.scala.html
- app/views/results/flowHistoryResults.scala.html
- app/views/results/flowMetricsHistoryResults.scala.html
- app/views/results/jobDetails.scala.html
- app/views/results/jobHistoryResults.scala.html
- app/views/results/oldFlowHistoryResults.scala.html
- app/views/results/oldFlowMetricsHistoryResults.scala.html
- app/views/tags/aggregatedMetrics.scala.html
- app/views/tags/pagination.scala.html
- app/views/tags/searchPanel.scala.html
- build.sbt
- compile.conf
- compile.sh
- web/app/templates/app.hbs
- web/app/templates/job.hbs
- web/app/templates/workflow.hbs
> Proxy friendly relative urls

- app/com/linkedin/drelephant/tuning/AutoTuningAPIHelper.java
- app/com/linkedin/drelephant/tuning/engine/SparkHBTParamRecommender.java
Adding buffer for memory parameters for spark HBT.
> Changing buffer for memory related parameter for Spark HBT

- app/controllers/Application.java
- conf/routes
In this PR there are changes made to implement REST Api endpoint ( /rest/sparkjobbestparam) for getting current best suggested param values. This Api takes` job definition id` as param and in response provide latest execution link with best params applied and the param itself. In case the job information is not found or there are no best parameter suggestions then Api will respond with HTTP code 404 with the respective reason.
**HOW THIS IS TESTED**
Tested the Api for some jobs using the POSTMAN tool and chrome browser.
> Implementing REST Api for getting Best params for given Job Definition Id

- app/com/linkedin/drelephant/tuning/AbstractFitnessManager.java
- app/com/linkedin/drelephant/tuning/TuningHelper.java
- app/com/linkedin/drelephant/tuning/hbt/AutoTuningFailureHandler.java
- app/com/linkedin/drelephant/tuning/hbt/FitnessManagerHBT.java
- app/com/linkedin/drelephant/tuning/hbt/NonAutoTuningFailureHandler.java
- app/models/JobExecution.java
- app/models/JobSuggestedParamSet.java
This PR is handling OptimisticWriteLockException in JobExecution and also improve logging in FitnessHBTManager
> Handling OptimisticWriteLockException and improving logging

- app-conf/FetcherConf.xml
- app/com/linkedin/drelephant/tony/data/TonyApplicationData.java
- app/com/linkedin/drelephant/tony/fetchers/TonyFetcher.java
- app/models/AppResult.java
- build.sbt
- project/Dependencies.scala
- test/com/linkedin/drelephant/tony/fetchers/TonyFetcherTest.java
* Implemented parsing of job history file and config file
* Added unit test
> Implement TonyFetcher

- test/com/linkedin/drelephant/exceptions/azkaban/AzkabanJobLogAnalyzerTest.java
Some tests were failing due to changes made in the #555 and in this PR changes are made to fix them.
> Fixing test for changes made to fix MR exception fingerprinting

- app/com/linkedin/drelephant/tony/TonyMetricsAggregator.java
- app/com/linkedin/drelephant/tony/data/TonyApplicationData.java
- app/com/linkedin/drelephant/tony/util/TonyUtils.java
- test/com/linkedin/drelephant/tony/TonyMetricsAggregatorTest.java
- test/com/linkedin/drelephant/tony/util/TonyUtilsTest.java
* Added check so that if taskDuration is negative, we skip calculating used and wasted resources for the task
* Updated task end time setting to fall back to using application end time is task end time is not available
* Added unit tests
> Fix #572: MysqlDataTruncation error when no TASK_FINISHED event for a TonY task

- app/com/linkedin/drelephant/tony/fetchers/TonyFetcher.java
- test/com/linkedin/drelephant/tony/fetchers/TonyFetcherTest.java
Tested locally. Added unit test.
> TonyFetcher should also check intermediate directory if job not found in finished directory #587

- app/com/linkedin/drelephant/util/InfoExtractor.java
Tested it on a real cluster and now TonY jobs have FlowHistory, Flow definition, and Flow execution links.
Cc: @UWFrankGu (I'm not able to add you as a Reviewer explicitly because you're not on the Dr. Elephant team: https://github.com/orgs/linkedin/teams/dr-elephant/members
> InfoExtractor should support TonY jobs #591

- app/com/linkedin/drelephant/tony/heuristics/TaskMemoryHeuristic.java
- test/com/linkedin/drelephant/tony/heuristics/TaskMemoryHeuristicTest.java
Added unit test.
The reason the map might have been null in the first place is due to https://github.com/linkedin/TonY/issues/330, which should be fixed in https://github.com/linkedin/TonY/pull/331.
> Fix #590: NPE in TonY TaskMemoryHeuristic 

- app/views/help/tony/helpTaskMemory.scala.html
Here's what the updated help page looks like:
> Improve TonY TaskMemoryHeuristic help page #603

- app/com/linkedin/drelephant/tony/heuristics/TaskMemoryHeuristic.java
- app/com/linkedin/drelephant/util/InfoExtractor.java
- app/views/help/tony/helpTaskMemory.scala.html
- baseline.conf
- test/com/linkedin/drelephant/tony/heuristics/TaskMemoryHeuristicTest.java
Cherry-picked #592, #598, #601, #604 into master.
> Merge TonY fixes to master

- app-conf/HeuristicConf.xml
- app/com/linkedin/drelephant/tony/TonyMetricsAggregator.java
- app/com/linkedin/drelephant/tony/fetchers/TonyFetcher.java
- app/com/linkedin/drelephant/tony/heuristics/TaskGPUHeuristic.java
- app/com/linkedin/drelephant/tony/heuristics/TaskMemoryHeuristic.java
- app/com/linkedin/drelephant/tony/util/TonyUtils.java
- app/views/help/tony/helpTaskGPU.scala.html
- project/Dependencies.scala
- test/com/linkedin/drelephant/tony/fetchers/TonyFetcherTest.java
- test/com/linkedin/drelephant/tony/util/TonyUtilsTest.java
#605 fixed NPE in TonYUtils
Bumped TonY dependency to 0.3.16
> #606 Integrated TonY GPU metrics to Dr. Elephant;

- app/com/linkedin/drelephant/spark/fetchers/SparkRestClient.scala
In this PR the changes are made to modify the pattern of REST calls to SHS. Currently all the REST calls to fetch JobData, ExecutorData, StageData, FailedTask information, Logdata are made parallely. The SHS works to serve these requests and fetches all the relative data from the Database which initially takes some considerable time which is usually more then ReadTImeout set in Dr.Elephant (5 seconds), which leads to requestTimeout on Dr.Elephant but these requests are still getting processed by SHS. In this way SHS is wasting its threads to process atleast four parallel REST requests per application, and this many times exhaust the SHS's ThreadPool.
Also when SHS succeeds in fetching data from DB for one REST call for a particular application then it will be fast to …
> Changing the pattern of REST calls to Spark History Server

- .travis.yml
- app/com/linkedin/drelephant/tuning/AutoTuningAPIHelper.java
- test/com/linkedin/drelephant/tuning/AutoTunerApiTestRunner.java
- test/resources/test-param-generate-data.sql
For more information please follow the link : 
https://docs.google.com/document/d/1ft1ccj1aKrCB0RttGSzStVCwckgyYVMR4XWy_tNmeTE/edit?usp=sharing
> Returning empty hashmap when best parameters are default parameters

- .travis.yml
- app-conf/SchedulerConf.xml
- app/com/linkedin/drelephant/clients/WorkflowClient.java
- app/com/linkedin/drelephant/clients/azkaban/AzkabanWorkflowClient.java
- app/com/linkedin/drelephant/exceptions/ExceptionFinder.java
- app/com/linkedin/drelephant/exceptions/HadoopException.java
- app/com/linkedin/drelephant/exceptions/azkaban/AzkabanJobLogAnalyzer.java
- app/com/linkedin/drelephant/exceptions/azkaban/JobLogException.java
- app/com/linkedin/drelephant/exceptions/core/ExceptionFingerprintingRunner.java
- app/com/linkedin/drelephant/exceptions/util/Constant.java
- app/com/linkedin/drelephant/exceptions/util/ExceptionInfo.java
- app/com/linkedin/drelephant/util/Utils.java
- app/controllers/api/v1/Web.java
- app/models/JobsExceptionFingerPrinting.java
- conf/evolutions/default/10.sql
- test/com/linkedin/drelephant/exceptions/azkaban/AzkabanJobLogAnalyzerTest.java
- test/com/linkedin/drelephant/tuning/IPSOManagerTestRunner.java
- test/common/DBTestUtil.java
- test/common/TestConstants.java
- test/controllers/WebTest.java
- test/resources/test-exception-fingerprinting.sql
The changes made in this PR are done to integrate the Spark and MR exception fingerprinting. After these changes, the `workflow-exception` API will provide the results for both MR and Spark jobs failure. Some changes are done to resolve the issues in the existing exception fingerprinting approach.
**How Changes are tested**
Added unit tests for added functionality.
Done end to end testing on EI machine.
> Integrating Spark and MR exception fingerprinting

- app/com/linkedin/drelephant/util/MemoryFormatUtils.java
- test/com/linkedin/drelephant/util/MemoryFormatUtilsTest.java
where error 
java.lang.IllegalArgumentException: The formatted string [1,000 MB] does not match with the regex  /([-+]?\d*\.?\d+(?:[eE][-+]?\d+)?)\s*((?:[T|G|M|K])?B?)?/
> for example specification 1,000 MB to 1000 MB , No comma separated here

- web/app/templates/workflow-exceptions.hbs
**Description**
UI changes for Spark exception fingerprinting
Changes are tested on the EI machine.
> UI changes for Spark exception fingerprinting

- app/models/AppHeuristicResult.java
The size of the id in the prod table of a cluster has exceeded the INT limit. In this PR changes are made to alter the datatype of the ID to handle much larger values.
**HOW THESE CHANGES ARE TESTED**
Done an EndToEnd testing on EI machine.
> Changing the type of ID for AppHeuristicResult model

- app/com/linkedin/drelephant/tuning/AbstractFitnessManager.java
- app/com/linkedin/drelephant/tuning/hbt/FitnessManagerHBT.java
In this PR the changes are made to fix the result of one condition which is to determine if there is a need to disable tuning for a job. Some changes are also made to correct some typo and remove redundant conditions.
> Fixing a condition used to disable TuneIn for HBT

- app/com/linkedin/drelephant/exceptions/ExceptionFinder.java
- app/com/linkedin/drelephant/exceptions/ExceptionFingerprinting.java
- app/com/linkedin/drelephant/exceptions/core/ExceptionFingerprintingFactory.java
- app/com/linkedin/drelephant/exceptions/core/ExceptionFingerprintingRunner.java
- app/com/linkedin/drelephant/exceptions/core/ExceptionFingerprintingSpark.java
- app/com/linkedin/drelephant/exceptions/core/RegexRule.java
- app/com/linkedin/drelephant/exceptions/util/Constant.java
- app/com/linkedin/drelephant/exceptions/util/ExceptionInfo.java
- app/com/linkedin/drelephant/exceptions/util/ExceptionUtils.java
- app/com/linkedin/drelephant/spark/data/SparkApplicationData.scala
- app/com/linkedin/drelephant/spark/data/SparkRestDerivedData.scala
- app/com/linkedin/drelephant/spark/fetchers/SparkRestClient.scala
- app/controllers/api/v1/JsonKeys.java
- app/controllers/api/v1/Web.java
- app/models/JobsExceptionFingerPrinting.java
- conf/evolutions/default/11.sql
- conf/evolutions/default/12.sql
- test/com/linkedin/drelephant/spark/exception/ExceptionFingerprintingRunnerTest.java
- test/com/linkedin/drelephant/spark/exception/ExceptionFingerprintingSparkTest.scala
- test/com/linkedin/drelephant/util/InfoExtractorTest.java
- test/controllers/WebTest.java
- test/resources/test-exception-fingerprinting.sql
- web/app/templates/components/map-reduce-exception.hbs
This PR is about exception fingerprinting enhancement . It incorporates several changes in Rest API of Dr Elephant to fetch exception for flow . 
For detail explanation ,please [refer](https://docs.google.com/document/d/13fRxjYoPn6SzsQHn8gNvq27eljqtVM3AGbPBjdDdbNA/edit) this
**It fixes following issues .** 
- ExceptionFinder throws exception “Unique expecting 0 or 1 results but got 2" at isExceptionPrintingDone
- getSparkJobExceptionDetails in Web.java throws exception “Unique expecting 0 or 1 results but got 2"
- Querying JHS for driver log some time returns “No Log found” 
**Following are the enhancements to the exception fingerprinting** 
- Adding information about origination of logs , and provide the same to the user , so that user/developer can also go to the log page. 
- Add user …
> Exception Fingerprinting enhancement

- app/controllers/Application.java
As per DSS-20070 this PR contains changes for modifying the logger statement type from ERROR to WARN.
> DSS-20070: Changing logger statement type from ERROR to WARN

- app/com/linkedin/drelephant/exceptions/azkaban/AzkabanJobLogAnalyzer.java
Fixing the regex pattern for MR exception fingerprinting
> Fixing the regex pattern for MR exception fingerprinting

- app/com/linkedin/drelephant/exceptions/util/ExceptionUtils.java
- project/build.properties
- test/com/linkedin/drelephant/spark/exception/ExceptionFingerprintingSparkTest.scala
This is hot fix for fixing the bug in SparkExceptionFingerprinting , where half of the exception stack trace is displayed as new exception . 
DSS-24595
> Fixing the bug in SparkExceptionFingerprinting 

- app/com/linkedin/drelephant/exceptions/core/ExceptionFingerprintingSpark.java
- test/com/linkedin/drelephant/spark/exception/ExceptionFingerprintingSparkTest.scala
- test/com/linkedin/drelephant/spark/exception/ExceptionFingerprintingSparkUtilities.scala
In this PR the changes are done to add the Job Diagnostic Message which is Dr.Elephant gets from RM, to the Spark Exceptionfingerprinting result. This is done as the Job Diagnostic Message mostly contains very helpful data regarding the reason for Job Failure and it would help users to reach the RCA for the failure.
**HOW THESE CHANGES ARE TESTED**
Added respective unit test cases for the changes made.
> [Enhancement]Addition of Job Diagnostic Message to Spark Exception Fingerprinting Result

- web/app/controllers/workflow-exceptions.js
- web/app/styles/app.css
- web/app/templates/job.hbs
- web/app/templates/workflow-exceptions.hbs
This PR contains changes done in the UI module for incorporating feedback providing for ExceptionFingerpritinng results for a flow. 
Some pics for reference:
**HOW CHANGES ARE TESTED**
Tested changes in the test environment.
> UI changes for feedback related to ExceptionFingerprinting result

- app/com/linkedin/drelephant/spark/heuristics/DriverHeuristic.scala
- test/com/linkedin/drelephant/spark/heuristics/DriverHeuristicTest.scala
Increasing buffer fraction in Spark Driver Memory Heuristic.
> Relaxing Buffer Fraction for Spark Driver Memory
